version: 0.2
env:
  parameter-store:
    DOCKER_USER: dockerhub-user
    DOCKER_TOKEN: dockerhub-token
    DB_HOST: ecs-laravel-db-host
    DB_PASSWORD: ecs-laravel-db-pass
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      ##### dockerリポジトリへのログイン ###################################
      # ECRのリポジトリにログイン
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

      ##### 環境変数の定義 ###################################
      # APP_NAME, APP_ENV はcodeBuildの環境変数を設定している。
      # envディレクティブで設定していないのはスクリプトで定義している部分があるため。
      # AWSのアカウントIDを$CODEBUILD_BUILD_ARNから取得
      - echo ${CODEBUILD_BUILD_ARN}
      - OLDIFS=$IFS && IFS=':' && set -- ${CODEBUILD_BUILD_ARN} && AWS_ACCOUNT_ID=$5 && IFS=$OLDIFS
      - ROOT_DIR=`pwd`
      - ECR_IMAGE_LARAVEL_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ecs-practice/laravel-study
      # gitのコミットハッシュを使ってdockerイメージ
      - COMMIT_HASH=`echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-9`
      # 下記のDockerfileが変更されていたらイメージをビルドしてECRへpushする
      - IMGDEF_JSON_FILE=${ROOT_DIR}/imagedefinitions.json
      # 環境変数初期値表示
      - |
        echo ">>> ENVs ->"
        echo ">>>     AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}"
        echo ">>>     ROOT_DIR: ${ROOT_DIR}"
        echo ">>>     ECR_IMAGE_LARAVEL_URI: ${ECR_IMAGE_LARAVEL_URI}"
        echo ">>>     COMMIT_HASH: ${COMMIT_HASH}"
        echo ">>>     IMGDEF_JSON_FILE: ${IMGDEF_JSON_FILE}"
      # migration様に.envを生成
      - touch ${ROOT_DIR}/laravel/.env
      - echo DB_HOST=${DB_HOST} >> ${ROOT_DIR}/laravel/.env
      - echo DB_PASSWORD=${DB_PASSWORD} >> ${ROOT_DIR}/laravel/.env
      - echo DB_CONNECTION=mysql >> ${ROOT_DIR}/laravel/.env
      - echo DB_PORT=3306 >> ${ROOT_DIR}/laravel/.env
      - echo DB_DATABASE=ecsdb >> ${ROOT_DIR}/laravel/.env
      - echo DB_USERNAME=root >> ${ROOT_DIR}/laravel/.env

  build:
    commands:
      - IMGDEF_JSON=""
      - cd ${ROOT_DIR}; echo ">>> [dir] `pwd`"
      
      ##### dockerイメージのビルド ###################################
      # Dockerfileが更新されていたらイメージをビルドしてECRへpush、されていなければlatestをpull
      - docker-compose -f docker-compose.prod.yaml up --build -d
      - docker exec laravel-study bash -c "php artisan migrate --force"
      - docker exec laravel-study bash -c "curl 127.0.0.1:3306"
      # - docker exec laravel-study bash -c "php artisan config:clear && php artisan cache:clear && php artisan migrate --env=testing --force"
      ##### Execute test ########################################
      - docker exec laravel-study bash -c "./vendor/bin/phpunit"
      - |
        set -e
        IMGDEF_JSON=${IMGDEF_JSON}$(printf '{"name":"%s", "imageUri": "%s"},' laravel ${ECR_IMAGE_LARAVEL_URI}:${COMMIT_HASH})
        docker tag laravel-study:test ${ECR_IMAGE_LARAVEL_URI}:${COMMIT_HASH}
        docker push ${ECR_IMAGE_LARAVEL_URI}:${COMMIT_HASH}

      ##### imagedefinitions.jsonの書き込み ###################################
      - IMGDEF_JSON="["${IMGDEF_JSON:0:${#IMGDEF_JSON}-1}"]"
      - echo ${IMGDEF_JSON}
      - echo ${IMGDEF_JSON} > ${IMGDEF_JSON_FILE}
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ${ROOT_DIR}

