version: '3.7'

services:
  laravel-study:
    container_name: laravel-study
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: 016992890397.dkr.ecr.ap-northeast-1.amazonaws.com/laravel:1.0.1
    networks:
    - laravel_study-network

  nginx-study:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: 016992890397.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:1.0.1
    container_name: nginx-study
    ports:
    - 80:80
    depends_on:
    - laravel-study
    networks:
    - laravel_study-network

  study-db:
    image: mysql:5.7
    container_name: study-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - study_mysql_volume:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
    - laravel_study-network

networks:
  laravel_study-network:
    driver: bridge
volumes:
  study_mysql_volume:
    driver: local
