version: '3.7'

services:
  laravel-study:
    container_name: laravel-study
    build:
      context: .
      dockerfile: Dockerfile.php
    image: laravel-study:test

  nginx-study:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx-study:test
    container_name: nginx-study
    ports:
    - 80:80

  study-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: study-db
    container_name: study-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
